# マウス操作有効
set-option -g mouse on

# prefixキーをC-qに変更
set -g prefix C-g
unbind C-b

bind \\ split-window -h
bind - split-window -v

set -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode C-v send -X rectangle-toggle
bind-key -T copy-mode y send -X copy-selection
set -s copy-command 'pbcopy'

# ステータスバーの右側の表示内容を空に設定
set -g status-right ""

# ステータスバーを上部に表示する
set -g status-position top
# checkhealth回避
set -g escape-time 10
set -g focus-events on

set-option -g status-left '#[fg=cyan,bg=colour60]#{?client_prefix,#[reverse],} tmux #[default]'

# ステータスバーの色を設定する
set -g status-bg "colour60"
set -g status-fg "colour236"
